const titles = {
  ar: {
    //Global

    open: "فتح",
    new: "جديد",
    form: "استمارة",
    paper: "صفحة",
    "pop-up": "تنبيه",
    filter: "فلتر",
    element: "عنصر",
    style: "نمط",
    cut: "قص",
    paste: "لصق",
    duplicate: "مضاعفة",

    // Header
    language: "Ar",
    chooseLanguage: "اختر اللغة",
    //Starter

    // Element Tool Bar
    container: "حاوية",

    library: "مكتبة",
    property: "خصائص",
    condition: "شروط",
    // Form Tool Bar
    // Title
    history: "العمليات",
    features: "المميزات",
    formName: "اسم الاستمارة",
    elementBuilder: "مصمم العناصر",
    select_edit: "تحديد / تحرير",
    preview: "العرض",

    //Button
    redo: "التالي",
    undo: "السابق",
    formNameHolder: "اختر اسم الاستمارة",

    //Leftsidebar
    //Button
    heading: "عنوان",
    askAnswer: "سؤال / جواب",
    info: "إشعار",
    header: "ترويسة",
    footer: "تذييل",
    table: "جدول",
    // Button Element
    shortText: "نص قصير",
    textArea: "مساحة نصية",
    text: "نص",
    button: "زر",
    image: "صورة",
    checkBox: "مربع الاختيار",
    radioChoice: "زر الاختيار",
    dropList: "قائمة منسدلة",
    uploadFile: "رفع ملف",
    signature: "توقيع",
    pageBreak: "فاصل صفحة",
    inputRange: "نطاق الإدخال",
    // Body Workplace
    // Element Container
    question_Text: "إضافة عنصر سؤال",
    answer_Text: "إضافة عنصر جواب",
    heading_Text: "إضافة عنصر عنوان",
    info_Text: "إضافة عنصر تعليمات",
    home: "الرئيسيه",
    about_us: "حولنا",
    contacts: "للتواصل",
    terms: "الأحكام",
    privacy: "الخصوصية",
    partner: "الشركاء",
    add: "اضافه",
    education: "تعليم",
    job: "عمل",
    login: "تسجيل الدخول",
    register: "انشاء حساب",
    username: "اسم المستخدم",
    password: "كلمه المرور",
    firstname: "الاسم",
    lastname: "الكنيه",
    email: "الايميل",
    address: "العنوان",
    country: "البلد",
    city: "المدينه",
    gender: "الجنس",
    male: "ذكر",
    female: "انثى",
    birth: "تاريخ الميلاد",
    phd: "الدكتوراه",
    master: "الماستر",
    bachelor: "الباكالوريوس",
    scholarship: "البعثات",
    mail: "البريد",
    inbox: "الوارد",
    outbox: "الصادر",
    pending: "المعلق",
    delete: "حذف",
    selectTypeHeading: "اختر نوع هذا المجلد",
    category: "فئه",
    categoryFilter: "فلتر الفئات",
    ChooseCategory: "اختيار الفئات",

    subFilter: "$$",
    tag: "$$",
    cancel: "الغاء",
    name: "الاسم",
    rename: "اعاده التسميه",
    catsTree: "شجره الفئات",
    catProps: "خصائص الصنف",
    catForms: "$$",
    confirm: "تأكيد",
    logoutMessage: "شكرا لزيارتك",
    logout: "تسجيل الخروج",
    userType: "نوع العميل",
    forms: "$$",
    subForms: "$$",
    addFormHeading: "$$",
    addFolderName: "$$",
    addNewForm: "$$",
    addNewFolder: "اضف مجلد جديد",
    noData: "لايوجد بيانات",
    formProps: "$$",
    public: "عام",
    private: "خاص",
    back: "رجوع",
    go: "بحث",
    copy: "نسخ",
    ok: "موافق",
    processing: "جار المعالجه ...",
    select: "اختيار",
    selectFormHeading: "$$",
    loading: "$$",
    newSave: "حفظ بملف جديد",
    askPlaceholder: "اكتب السؤال هنا ...",
    shortTextPopupPlaceholder: "$$",
    save: "حفظ",
    requiredField: "هذا الحقل مطلوب",
    shortTextPopupHeading: "$$",
    shortTextPopupAsk: "اكتب سؤالك هنا ...",
    discardChanges: "تجاهل التغييرات",
    id: "$$",
    options: "الخيارات",
    dropDowns: "القوائم",
    answers: "الاجابات",
    translator: "$$",
    noActiveItem: "اختر استمارة لبدء الترجمة",
    selectLang: "$$",
    choices: "الخيارات",
    imagePopup: "$$",
    symbol: "شعار",
    imgPopupTextarea: "$$",
    filePopup: "$$",
    signature_placeholder: "$$",
    clear: "$$",
    generalDiscription: "$$",
    generalDiscriptionPlaceholder: "$$",
    block: "$$",
    grid: "جدول",
    block_Text: "$$",
    chooseDiminssions: "اختر الابعاد",
    rows: "الاسطر",
    columns: "الاعمده",
    color: "لون",
    width: "العرض",
    height: "الارتفاع",
    customize_checkbox: "$$",
    uploadSvg: "Upload Svg",
    addAnswer: "إضافة جواب",
    exportPdf: "تصدير",
    placeholder: "$$",
    number: "عدد",
    date: "تاريخ",
    textBlock: "نص",
    formDetailsSavePersist: "الخروج والتخزين لوقت لاحق",
    formDetailsExitMessage: "هل تريد مغادره الصفحه ؟",
    formDetailsExitTitle: "الرجوع للصفحه الرئيسيه",
    login_register: "الدخول\nالتسجيل",
    settings: "الاعدادات"
  },
  en: {
    //Global
    open: "Open",
    new: "New",
    form: "Form",
    paper: "Page",
    "pop-up": "Pop-up",
    filter: "Filter",
    element: "Element",
    style: "Style",
    cut: "Cut",
    paste: "Paste",
    duplicate: "Duplicate",

    // Header
    language: "En",
    chooseLanguage: "Choose language",
    //Starter

    // Element Tool
    container: "Container",

    library: "Library",
    property: "Property",
    condition: "Condition",
    // Form Tool Bar
    // Title
    history: "History",
    features: "Features",
    formName: "Form name",
    elementBuilder: "Element builder",
    select_edit: "Select / Edit",
    preview: "Preview",
    //Button
    redo: "Redo",
    undo: "Undo",
    formNameHolder: "Choose form name",

    //Leftsidebar
    //Button
    heading: "Heading",
    askAnswer: "Ask / Answer",
    info: "Notification",
    header: "Header",
    footer: "Footer",
    table: "Table",
    // Button Element
    shortText: "Short text",
    textArea: "Text block",
    text: "Text",
    button: "Button",
    image: "Image",
    checkBox: "Checkbox",
    radioChoice: "Radio choice",
    dropList: "Drop-down list",
    uploadFile: "Upload file",
    signature: "Signature",
    pageBreak: "Page break",
    inputRange: "Input range",
    // Body Workplace
    // Element Container
    question_Text: "Add a question element",
    answer_Text: "Add an answer element",
    heading_Text: "Add heading element",
    info_Text: "Add information element",
    home: "Home",
    about_us: "About us",
    contacts: "Contacts",
    terms: "Terms",
    privacy: "Privacy",
    partner: "Partner",
    add: "Add",
    education: "Education",
    job: "Job",
    login: "Login",
    register: "Register",
    username: "Username",
    password: "Password",
    firstname: "First name",
    lastname: "Last name",
    email: "Email",
    address: "Address",
    country: "Country",
    city: "City",
    gender: "Gender",
    male: "Male",
    female: "Female",
    birth: "Birth date",
    phd: "Phd",
    master: "Master",
    bachelor: "Bachelor",
    scholarship: "Scholarship",
    mail: "Mail",
    inbox: "Inbox",
    outbox: "Outbox",
    pending: "Pending",
    delete: "Delete",
    selectTypeHeading: "Select folder type ",
    category: "Category",
    categoryFilter: "Category filter",
    ChooseCategory: "Choose Category",
    subFilter: "Sub-filter",
    tag: "Tag",
    cancel: "Cancel",
    name: "Name",
    rename: "Rename",
    catsTree: "Categories tree",
    catProps: "Category properties",
    catForms: "Category forms",
    confirm: "Confirm",
    logoutMessage: "Thanks for visiting",
    logout: "Logout",
    userType: "User type",
    forms: "Forms",
    subForms: "Sub-forms",
    addFormHeading: "Form name",
    addFolderName: "Folder name",
    addNewForm: "Add new Form",
    addNewFolder: "Add new Folder",
    noData: "No Data",
    formProps: "Form properties",
    public: "Public",
    private: "Private",
    back: "Back",
    go: "Go",
    copy: "Copy",
    ok: "Ok",
    processing: "Processing ...",
    select: "Select",
    selectFormHeading: "Select a form",
    loading: "Loading",
    newSave: "Save to new file",
    askPlaceholder: "Write your question here ...",
    shortTextPopupPlaceholder: "Write an id for this field ...",
    save: "Save",
    requiredField: "This field is required",
    shortTextPopupHeading: "Fill in information",
    shortTextPopupAsk: "Write your question here ...",
    discardChanges: "Discard changes",
    id: "id",
    options: "Options",
    dropDowns: "Drop downs",
    answers: "Answers",
    translator: "Translator",
    noActiveItem: "Choos form to start translate",
    selectLang: "Select Language",
    choices: "Choices",
    imagePopup: "Upload your image",
    symbol: "Symbol",
    imgPopupTextarea: "Description ...",
    filePopup: "File",
    signature_placeholder: "Write your signature here ...",
    generalDiscription: "General Discription",
    clear: "Clear",
    generalDiscriptionPlaceholder: "Write your discription here ...",
    block: "Block",
    grid: "Grid",
    block_Text: "Block Element",
    chooseDiminssions: "Choose Diminssions",
    rows: "Rows",
    columns: "Columns",
    color: "color",
    width: "Width",
    height: "Height",
    customize_checkbox: "Customize",
    uploadSvg: "$$",
    addAnswer: "Add answer",
    exportPdf: "Export As PDF",
    placeholder: "Placeholder",
    number: "Number",
    date: "Date",
    textBlock: "Text Block",
    formDetailsSavePersist: "Exit and save for later",
    formDetailsExitMessage: "Back to home page",
    formDetailsExitTitle: "Are you sure you want to leave this page ?",
    settings: "Settings",
    login_register: "Login\nRegister"
  },
  gr: {
    //Global
    open: "Öffnen",
    new: "Neu",
    form: "Formular",
    paper: "Seite",
    "pop-up": "Pop-up",
    filter: "Filter",
    element: "Element",
    style: "Stil",
    cut: "Ausschneiden",
    paste: "Einfügen",
    duplicate: "Duplizieren",

    // Header
    language: "De",
    chooseLanguage: "Sprache auswählen",
    //Starter

    // Element Tool Bar
    container: "Container",

    library: "Bibliothek",
    property: "Eigenschaft",
    condition: "Bedingung",
    // Form Tool Bar
    // Title
    history: "Verlauf",
    features: "Merkmal",
    formName: "Formularname",
    elementBuilder: "Elementersteller",
    select_edit: "Auswählen / Bearbeiten",
    preview: "Vorschau",

    //Button
    redo: "Wiederholen",
    undo: "Rückgängig",
    formNameHolder: "Geben Sie dem Formular einen Namen",

    //Leftsidebar
    //Button
    heading: "Überschrift",
    askAnswer: "Frage / Antwort",
    info: "Benachrichtigung",
    header: "Kopfzeile",
    footer: "Fußzeile",
    table: "Tabelle",
    // Button Element
    shortText: "Kurzer Text",
    textArea: "Textblock",
    text: "Text",
    button: "Taste",
    image: "Bild",
    checkBox: "Checkbox",
    radioChoice: "Optionsfeld",
    dropList: "Dropdown-Liste",
    uploadFile: "Datei hochladen",
    signature: "Unterschrift",
    pageBreak: "Seitenumbruch",
    inputRange: "Eingabebereich",
    // Body Workplace
    // Element Container
    question_Text: "Frageelement hinzufügen",
    answer_Text: "Antwortelement hinzufügen",
    heading_Text: "Überschriftenelement hinzufügen",
    info_Text: "Informationselement hinzufügen",
    home: "Home",
    about_us: "Über uns",
    contacts: "Kontakte",
    terms: "Impressum",
    privacy: "Datenschutz",
    partner: "Partner",
    add: "Hinzufügen",
    education: "Ausbildung",
    job: "Job",
    login: "Anmelden",
    register: "Registrierung",
    username: "Benutzername",
    password: "Passwort",
    firstname: "Vorname",
    lastname: "Nachname",
    email: "E-Mail",
    address: "Adresse",
    country: "Land",
    city: "Stadt",
    gender: "Geschlecht",
    male: "Männlich",
    female: "Weiblich",
    birth: "Geburtsdatum",
    phd: "Doktor",
    master: "Master",
    bachelor: "Bachelor",
    scholarship: "Stipendium",
    mail: "Post",
    inbox: "Posteingang",
    outbox: "Postausgang",
    pending: "Ausstehend",
    delete: "Löschen",
    selectTypeHeading: "Ordnertyp auswählen",
    category: "Kategorie",
    categoryFilter: "Kategorie filter",
    ChooseCategory: "Kategorie wählen",
    subFilter: "Unterfilter",
    tag: "Tag",
    cancel: "Abbrechen",
    name: "Name",
    rename: "Umbenennen",
    catsTree: "Kategorienbaum",
    catProps: "Kategorieneigenschaften",
    catForms: "Kategorienformen",
    confirm: "Bestätigen",
    logoutMessage: "Vielen Dank für Ihren Besuch",
    logout: "Abmeldung",
    userType: "Benutzertyp",
    forms: "Anträge",
    subForms: "Unteranträge",
    addFormHeading: "Antragsname",
    addFolderName: "Ordnername",
    addNewForm: "$$",
    addNewFolder: "$$",
    noData: "KeineAngaben",
    formProps: "Antragseigenschaften",
    public: "Öffentlich",
    private: "Privat",
    back: "Zurück",
    go: "Weiter",
    copy: "Kopieren",
    ok: "Ok",
    processing: "Bearbeitung...",
    select: "Auswählen",
    selectFormHeading: "Überschrift des Antrags auswählen",
    loading: "Laden",
    newSave: "Speichern unter",
    askPlaceholder: "Schreiben Sie Ihre Antwort hier",
    shortTextPopupPlaceholder: "Fügen Sie zu diesem Felde eine ID hinzu",
    save: "Speichern",
    requiredField: "Pflichtfeld",
    shortTextPopupHeading: "Bitte ausfüllen",
    shortTextPopupAsk: "Bitte hier eine Frage einfügen",
    discardChanges: "Änderungen ablehnen",
    id: "ID",
    options: "Optionen",
    dropDowns: "Drop-downs",
    answers: "Antworten",
    translator: "Übersetzer",
    noActiveItem: "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
    selectLang: "LangAuswählen",
    choices: "Auswahlmöglichkeiten",
    imagePopup: "BildPopup",
    symbol: "Symbol",
    imgPopupTextarea: "BildPopupTextbereich",
    filePopup: "DateiPopup",
    signature_placeholder: "UnterschriftenPlatzhalter",
    clear: "bereiningen",
    generalDiscription: "Hauptbeschreibung",
    generalDiscriptionPlaceholder: "HauptbeschreibungPlatzhalter",
    block: "Block",
    grid: "Gitter",
    block_Text: "TextBlocken",
    chooseDimensions: "DimensionenAuswählen",
    rows: "Reihen",
    columns: "Spalten",
    color: "Farbe",
    width: "Breite",
    height: "Höhe",
    customize_checkbox: "CheckBoxAnpassen",
    addAnswer: "$$$",
    exportPdf: "$$",
    placeholder: "$$",
    number: "Number",
    date: "Date",
    textBlock: "$$",
    formDetailsSavePersist: "$$",
    formDetailsExitMessage: "$$",
    formDetailsExitTitle: "$$",
    login_register: "Login\nRegister",
    settings: "Einstellungen"
  }
};

export default titles;
